server:
  port: 8080

  cors:
    allowCredentials: true
    allowMethods: ["GET", "POST", "DELETE"]
    allowHeaders: ["Origin", "Content-Length", "Content-Type"]
    maxAge: 12h

map:
  bounds:
    southWest: 
      latitude: 57.814671
      longitude: 39.390803
    northEast: 
      latitude: 57.937349
      longitude: 39.689861

  defaultPosition: 
    latitude: 57.860866
    longitude: 39.514879

  zoom:
    default: 16
    min: 14
    max: 18

playgrounds:
  criticalTimeLimit: 168h  # 7 days
  pathToFile: ./resources/playgrounds.csv

googleDrive:
  pathToGoogleServiceAccount: ./key.json

form:
  maxSize: 15mb
  maxPhotos: 6

logger:
  output: ./log/safechildhood.log
  outputErrors: ./log/safechildhood.log